function [droll,dpitch,dyaw] = dMatrix_to_dEuler(in1,in2)
%DMATRIX_TO_DEULER
%    [DROLL,DPITCH,DYAW] = DMATRIX_TO_DEULER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Jul-2017 13:07:12

dr1_1 = in2(1);
dr1_2 = in2(4);
dr1_3 = in2(7);
dr2_3 = in2(8);
dr3_3 = in2(9);
r1_1 = in1(1);
r1_2 = in1(4);
r1_3 = in1(7);
r2_3 = in1(8);
r3_3 = in1(9);
t4 = imag(r2_3);
t5 = real(r3_3);
t2 = t4+t5;
t7 = imag(r3_3);
t8 = real(r2_3);
t3 = t7-t8;
t6 = t2.^2;
t9 = t3.^2;
t10 = t6+t9;
t11 = 1.0./t10;
droll = -dr2_3.*t2.*t11-dr3_3.*t3.*t11;
if nargout > 1
    dpitch = dr1_3.*1.0./sqrt(-r1_3.^2+1.0);
end
if nargout > 2
    t14 = imag(r1_2);
    t15 = real(r1_1);
    t12 = t14+t15;
    t17 = imag(r1_1);
    t18 = real(r1_2);
    t13 = t17-t18;
    t16 = t12.^2;
    t19 = t13.^2;
    t20 = t16+t19;
    t21 = 1.0./t20;
    dyaw = -dr1_1.*t13.*t21-dr1_2.*t12.*t21;
end
