function [roll,pitch,yaw] = Matrix_to_Euler(in1)
%MATRIX_TO_EULER
%    [ROLL,PITCH,YAW] = MATRIX_TO_EULER(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Jul-2017 13:07:11

r1_1 = in1(1);
r1_2 = in1(4);
r1_3 = in1(7);
r2_3 = in1(8);
r3_3 = in1(9);
roll = angle(r2_3.*-1i+r3_3);
if nargout > 1
    pitch = asin(r1_3);
end
if nargout > 2
    yaw = angle(r1_1-r1_2.*1i);
end
