function dq = AngularVelocity_to_EulerRates(in1,in2)
%ANGULARVELOCITY_TO_EULERRATES
%    DQ = ANGULARVELOCITY_TO_EULERRATES(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Jun-2017 12:58:34

qy = in1(2,:);
qz = in1(3,:);
wx = in2(1,:);
wy = in2(2,:);
wz = in2(3,:);
t2 = cos(qz);
t3 = sin(qz);
t4 = cos(qy);
t5 = 1.0./t4;
t6 = sin(qy);
dq = [t5.*(t2.*wx-t3.*wy);t3.*wx+t2.*wy;t5.*(t4.*wz-t2.*t6.*wx+t3.*t6.*wy)];
