function [dqLA,dqLL] = FK_dqFlexion_dqKnee_to_dqLA_dqLL(qFlexion,qKnee,dqFlexion,dqKnee)
%FK_DQFLEXION_DQKNEE_TO_DQLA_DQLL
%    [DQLA,DQLL] = FK_DQFLEXION_DQKNEE_TO_DQLA_DQLL(QFLEXION,QKNEE,DQFLEXION,DQKNEE)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jun-2017 15:57:21

t2 = qFlexion+qKnee;
t3 = 2.562548466390441e5;
t4 = pi.*(1.3e1./1.8e2);
t5 = atan(2.372270238835302e-1);
t6 = 5.000630060302402e3;
t7 = atan(1.360242179616549e-1);
t8 = qKnee+t7;
t9 = qKnee-t4+t5;
t10 = cos(t8);
t11 = t6.*t10.*2.4e3;
t12 = 5.124451190127583e1;
t13 = atan(5.0./5.1e1);
t14 = t4-t13;
t15 = cos(t14);
t16 = t12.*t15.*1.92e5;
t17 = cos(t2);
t18 = sin(t2);
t19 = qFlexion+t4;
t20 = cos(t9);
t21 = t3.*t20.*1.6e2;
t22 = t11+t16+t21+4.3252701e7;
t23 = t17.*6.74e2;
t24 = t18.*4.955e3;
t25 = cos(t19);
t26 = sin(qFlexion);
t27 = t26.*1.2e3;
t28 = sin(t19);
t29 = t28.*4.08e3;
t32 = t25.*4.0e2;
t30 = t23+t24+t27+t29-t32;
t31 = 1.0./t22;
t33 = t30.^2;
t34 = -t31.*t33+1.0;
t35 = 1.0./sqrt(t34);
t36 = t17.*4.955e3;
t37 = t18.*6.74e2;
t38 = pi.*(7.7e1./1.8e2);
t39 = qKnee+t38;
t40 = 1.0./sqrt(t22);
dqLA = dqKnee.*t35.*((t36-t37).*1.0./sqrt(t11+t16+t3.*cos(qKnee+t5-pi.*(1.3e1./1.8e2)).*1.6e2+4.3252701e7)+1.0./t22.^(3.0./2.0).*t30.*(t3.*sin(t9).*1.6e2+t6.*sin(t8).*2.4e3).*(1.0./2.0))+dqFlexion.*t35.*t40.*(t25.*4.08e3+t28.*4.0e2+t36-t37+cos(qFlexion).*1.2e3);
if nargout > 1
    dqLL = dqKnee.*t40.*(cos(qKnee).*1.011e4-cos(t39).*2.49335e5+sin(qKnee).*7.4325e4+sin(t39).*5.9149e4).*(-1.0./1.25e2);
end
