function hip_flexion_to_toe = FK_hipflexion_to_toe(qFlexion,qKnee)
%FK_HIPFLEXION_TO_TOE
%    HIP_FLEXION_TO_TOE = FK_HIPFLEXION_TO_TOE(QFLEXION,QKNEE)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jun-2017 15:57:20

t2 = cos(qFlexion);
t3 = cos(qKnee);
t4 = sin(qFlexion);
t5 = sin(qKnee);
t8 = pi.*(1.3e1./1.8e2);
t6 = qKnee-t8;
t7 = cos(t6);
t9 = t2.*t5;
t10 = t3.*t4;
t11 = t9+t10;
t12 = sin(t6);
t13 = t2.*t3;
t15 = t4.*t5;
t14 = t13-t15;
hip_flexion_to_toe = [t4.*(3.0./2.5e1)+t2.*t3.*6.74e-2+t2.*t5.*4.955e-1+t3.*t4.*4.955e-1-t4.*t5.*6.74e-2+t7.*t11.*(5.1e1./1.25e2)-t7.*t14.*(1.0./2.5e1)-t11.*t12.*(1.0./2.5e1)-t12.*t14.*(5.1e1./1.25e2);t2.*(-3.0./2.5e1)-t2.*t3.*4.955e-1+t2.*t5.*6.74e-2+t3.*t4.*6.74e-2+t4.*t5.*4.955e-1-t7.*t11.*(1.0./2.5e1)-t7.*t14.*(5.1e1./1.25e2)-t11.*t12.*(5.1e1./1.25e2)+t12.*t14.*(1.0./2.5e1)];
