function [qLA,qLL] = FK_qFlexion_qKnee_to_qLA_qLL(qFlexion,qKnee)
%FK_QFLEXION_QKNEE_TO_QLA_QLL
%    [QLA,QLL] = FK_QFLEXION_QKNEE_TO_QLA_QLL(QFLEXION,QKNEE)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jun-2017 15:57:21

t2 = qFlexion+qKnee;
t3 = pi.*(1.3e1./1.8e2);
t4 = qFlexion+t3;
qLA = asin(1.0./sqrt(2.562548466390441e5.*cos(qKnee-pi.*(1.3e1./1.8e2)+atan(2.372270238835302e-1)).*1.6e2+5.000630060302402e3.*cos(qKnee+atan(1.360242179616549e-1)).*2.4e3+5.124451190127583e1.*cos(t3-atan(5.0./5.1e1)).*1.92e5+4.3252701e7).*(cos(t2).*6.74e2-cos(t4).*4.0e2+sin(qFlexion).*1.2e3+sin(t2).*4.955e3+sin(t4).*4.08e3));
if nargout > 1
    t5 = cos(t3);
    t6 = cos(qKnee);
    t7 = sin(qKnee);
    t8 = sin(t3);
    qLL = sqrt(t5.*9.792e-2+t6.*1.1892e-1-t7.*1.6176e-2+t8.*(6.0./6.25e2)+t5.*t6.*3.98936e-1-t5.*t7.*9.46384e-2+t6.*t8.*9.46384e-2+t7.*t8.*3.98936e-1+4.3252701e-1);
end
