function dqKnee = IK_dqLL_to_dqKnee(qLL,dqLL)
%IK_DQLL_TO_DQKNEE
%    DQKNEE = IK_DQLL_TO_DQKNEE(QLL,DQLL)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jun-2017 15:57:25

t2 = pi.*(1.3e1./1.8e2);
t3 = cos(t2);
t4 = sin(t2);
t5 = qLL.^2;
t11 = t3.*1.32385901184e14;
t12 = t4.*1.297900992e13;
t13 = t3.*t5.*1.9584e15;
t14 = t4.*t5.*1.92e14;
t15 = t3.^2;
t16 = t15.*1.5851803245056e15;
t17 = t4.^2;
t18 = t17.*1.6801419885056e15;
t19 = t3.*t4.*1.880064e13;
t20 = t5.*8.6505402e15;
t21 = t5.^2;
t22 = t21.*1.0e16;
t23 = t11+t12+t13+t14+t16+t18-t19+t20-t22-1.726759850035401e15;
t24 = t3.*9.46384e6;
t25 = t4.*3.98936e7;
t26 = sqrt(t23);
t6 = t24-t25+t26+1.6176e6;
t7 = t3.*3.01016e7;
t8 = t4.*8.50384e6;
t9 = t5.*1.0e8;
t10 = t7+t8+t9-3.1360701e7;
t27 = 1.0./t10.^2;
dqKnee = (dqLL.*((1.0./sqrt(t23).*(qLL.*1.73010804e16+qLL.*t3.*3.9168e15+qLL.*t4.*3.84e14-qLL.*t5.*4.0e16).*(1.0./2.0))./t10-qLL.*t6.*t27.*2.0e8).*-2.0)./(t6.^2.*t27+1.0);
