function qFlexion = IK_qLA_qKnee_to_qFlexion(qLA,qKnee)
%IK_QLA_QKNEE_TO_QFLEXION
%    QFLEXION = IK_QLA_QKNEE_TO_QFLEXION(QLA,QKNEE)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jun-2017 15:57:29

t2 = 5.124451190127583e1;
t3 = atan(5.0./5.1e1);
t4 = 5.000630060302402e3;
t5 = pi.*(1.3e1./1.8e2);
t6 = cos(qLA);
t7 = cos(t5);
t8 = sin(t5);
t9 = cos(qKnee);
t10 = sin(qKnee);
qFlexion = atan((t7.*4.08e3+t8.*4.0e2+t9.*4.955e3-t10.*6.74e2-sqrt(t6.^2.*(t7.*9.792e6+t8.*9.6e5+t9.*1.1892e7-t10.*1.6176e6+t7.*t9.*3.98936e7-t7.*t10.*9.46384e6+t8.*t9.*9.46384e6+t8.*t10.*3.98936e7+4.3252701e7))+1.2e3)./(sin(qLA).*sqrt(2.562548466390441e5.*cos(qKnee-pi.*(1.3e1./1.8e2)+atan(2.372270238835302e-1)).*1.6e2+t4.*cos(qKnee+atan(1.360242179616549e-1)).*2.4e3+t2.*cos(-t3+t5).*1.92e5+4.3252701e7)+t2.*cos(t3+pi.*(7.7e1./1.8e2)).*8.0e1+t4.*cos(qKnee-atan(7.351632047477745)))).*2.0;
